apiVersion: v1
name: kruise
description: Helm chart for kruise components
version: 0.9.0
icon: http://openkruise.io/img/kruise_white.png
keywords:
  - kubernetes
  - kruise
  - workload
  - statefulset
  - sidecar
  - job
  - deployment
home: https://openkruise.io
sources:
  - https://github.com/openkruise/kruise
