# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apps.kruise.io_clonesets.yaml
- bases/apps.kruise.io_broadcastjobs.yaml
- bases/apps.kruise.io_sidecarsets.yaml
- bases/apps.kruise.io_statefulsets.yaml
- bases/apps.kruise.io_uniteddeployments.yaml
- bases/apps.kruise.io_daemonsets.yaml
- bases/apps.kruise.io_nodeimages.yaml
- bases/apps.kruise.io_imagepulljobs.yaml
- bases/apps.kruise.io_advancedcronjobs.yaml
- bases/apps.kruise.io_containerrecreaterequests.yaml
- bases/policy.kruise.io_podunavailablebudgets.yaml
- bases/apps.kruise.io_resourcedistributions.yaml
- bases/apps.kruise.io_workloadspreads.yaml
- bases/apps.kruise.io_podmarkers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_clonesets.yaml
#- patches/webhook_in_broadcastjobs.yaml
#- patches/webhook_in_sidecarsets.yaml
- patches/webhook_in_statefulsets.yaml
#- patches/webhook_in_uniteddeployments.yaml
#- patches/webhook_in_daemonsets.yaml
#- patches/webhook_in_nodeimages.yaml
#- patches/webhook_in_imagepulljobs.yaml
#- patches/webhook_in_advancedcronjobs.yaml
#- patches/webhook_in_containerrecreaterequests.yaml
#- patches/webhook_in_resourcedistributions.yaml
#- patches/webhook_in_workloadspreads.yaml
#- patches/webhook_in_podmarkers.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_clonesets.yaml
#- patches/cainjection_in_broadcastjobs.yaml
#- patches/cainjection_in_sidecarsets.yaml
#- patches/cainjection_in_statefulsets.yaml
#- patches/cainjection_in_uniteddeployments.yaml
#- patches/cainjection_in_daemonsets.yaml
#- patches/cainjection_in_nodeimages.yaml
#- patches/cainjection_in_imagepulljobs.yaml
#- patches/cainjection_in_advancedcronjobs.yaml
#- patches/cainjection_in_containerrecreaterequests.yaml
#- patches/cainjection_in_resourcedistributions.yaml
#- patches/cainjection_in_workloadspreads.yaml
#- patches/cainjection_in_podmarkers.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
