name: "Create cluster using KinD"
on: push

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.1.0
    - name: setup-k8s
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        echo $KUBECONFIG
        kubectl cluster-info
        kubectl get pods -n kube-system
    - name: e2e-test
      run: |
        APP_PATH=/home/runner/go/src/github.com/openkruise/kruise
        mkdir -p $APP_PATH
        cp -r ./ $APP_PATH
        cd $APP_PATH
        go test ./test/e2e/ -v -args "-kubeconfig=/home/runner/.kube/kind-config-kind"